image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo "PATH=/home/gitpod/.pyenv/shims:/home/gitpod/.pyenv/bin:$PATH:/home/gitpod/.local/bin" >> ~/.bashrc && poetry install
    command: poetry shell

vscode:
  extensions:
    - ms-python.python
    - rebornix.ruby
    - wingrunr21.vscode-ruby
    - ms-python.debugpy
