#!/bin/bash

github_changelog_generator --user tayjaybabee --token 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 --project Inspyre-Toolbox --future-release 1.2.1-alpha.3 --bug-labels Bug::Confirmed,DevTask::Bug --include-tags-regex "ALL"
