{ % set name = "Inspyre-Toolbox" % }
  { % set version = "1.0" % }

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 1.0
  git_url: https://github.com/tayjaybabee/Inspyre-Toolbox.git

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/tayjaybabee/Inspyre-Toolbox
  license: WTFPL
