name: Publish to PyPi


on:
    release:
        types: [published]


jobs:
    publish:
        if: "!github.event.release.prerelease"
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.x'

            - name: Install Poetry
              run:  |
                python -m pip install --upgrade pip
                pip install poetry
                
            - name: Configure Poetry
              run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
              
            - name: Build and Publish
              run: |
                  set -e  # Exit immediately on non-zero exit-code.
                  poetry publish --build || { echo "Publishing to PyPi failed!"; exit 1; }
              
            - name: Generate Documentation
              run: |
                poetry run sphinx-apidoc -o docs/source inspyre_toolbox
                poetry run sphinx-build -b html docs/source docs/build
